### ISSUE TITLE
Distribuição

### ISSUE THREAD

**Issue by IvanIFJ** [iclinic/axiom#8]
## Definir formato de build e distribuição de design tokens

Issue para discussão sobre como será a distribuição dos tokens. 
Trouxe uma sugestão olhando para o PR https://github.com/iclinic/axiom/pull/4. O que acham?

Global tokens
```tsx
import { color } from '@iclinic/axiom/tokens/global'

color // { gray, red, green, yellow, blue, purple, alfaWhite, alfaBlack }
color.blue //  { 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160 }
```

Themes
```tsx
import { color, shadow } from '@iclinic/axiom/themes/core'

color // { brand, interactive, typeface, surface, icon, border, background, link, focus, highlight, others }
color.brand // { 10, 20, 30, 40, 50, 60 , 70, 80, 90, 100, 110, 130, 140, 150, 160 }

shadow.level // { 1, 2, 3, 4, 5, 6 }


// other themes
import { color } from '@iclinic/axiom/themes/light'
import { color } from '@iclinic/axiom/themes/dark'
```

Components
```tsx
// Base Components
import { Card, Button } from '@iclinic/axiom/components/base'

// Ui Components
import { Dialog, DatePicker } from '@iclinic/axiom/components/ui'
```

**Comment by gabriel-product-designer** [comment]
Fala pessoal, conversa boa aqui hein!!! 
Acho que tocaram em três pontos super importantes e vou tentar clarificar um pouco cada um deles. Lembrando que não existe receita então podemos alterar e ajustar tudo a nossa maneira. Apenas vou contribuir com minha bagagem!

 **TOKENS**  
 Quando falamos de tokens, temos dentro do Axiom duas camadas, a global e a core.  
 
 Os global tokens são nossas opções de estilo. Cores, bordas, opacidade, atributos de Font, sombras etc…em sua maioria esses tokens recebem semânticas bem primitivas como por exemplo Blue 60 para um hexa de uma cor azul.  
 
 Já na camada core, possuímos nossos Alias tokens que indicam sua aplicação de uso, como por exemplo, para um  background de um componente botão, eu poderia fazer uso do token $color.interactive.accent.default, ou para a borda de um campo de texto ativo, utlizar o token de cor $color.border.actived, por isso podemos os considerar que os core tokens são nossos tokens de decisão. Eles reforçam as cores da nossa marca, interações e todas as outras decisões de uso previstas que nos ajudam a compor nosso componentes.
 
   **COMPONENTS**  
   Quando falamos de componentes temos os base componentes e os componentes  .
   
   Base componentes: são os componentes moleculares como botões, inputs, selects, radius, tooltips, switchs, links, ícones, chips etc…

Componentes: são os componentes formados por mais de um base componente. Exemplo, um card de login, um menu de navegação, uma tabela, um card de seleção….e por ai vai.  

Vale ressaltar que existem outras abordagens como a classificação molecular ou mesmo a de categorização de natureza dos compoenentes. Mas essa nos ajuda a simplificar um pouco o entendimento no dia a dia.

**GERENCIAMENTO DE BIBLIOTECAS**

Para organizarmos nossas bibliotecas de componentes, separamos em três níveis. Core components, Team components e Not In D.S.

Core components: 
A biblioteca core é onde colocamos todos os componentes compartilhados entre todas as frentes de produto. Por exemplo todos os produtos utilizam o componente botão, portanto esse componente deve estar em nossa biblioteca core.
 
 Team Components:  
 Na biblioteca de team componente é onde colocamos aqueles componentes criadores para atender usos específicos de uma frente única do produto. Por exemplo, vamos imaginar um componente de tabela que seja utilizado em um contexto específico do módulo financeiro e nenhum dos outros módulos do nosso produto tenham necessidade do uso de tabela. logo não faz sentido distribui-lo para todos as outros frentes do nosso produto e portanto esse deve estar alocado em nosso biblioteca de team componentes.  
 
 Porém, um ponto a se atentar é que um componente de time pode ser promovido para a biblioteca core, caso outros times comecem a necessitar e utilizar aquele componente antes criado apenas para atender a um produto específico. 

Not In DS:
 Esse diz respeito aquele componente criado para atender algo tão pontual e sem recorrência de uso, que não se faz necessário nem mesmo componentiza-lo. Vale ressaltar que esse deve sim ser composto por tokens porém não necessita de grande complexidade de documentação ou coisa do tipo pois esse não será reutilizado em nenhum outro contexto.


Espero ter ajudado família! Tamo juntãooooooooo e qualquer dúvida contem comigo.
